version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@date-io/date-fns"
    versions:
    - ">= 2.a, < 3"
  - dependency-name: date-fns
    versions:
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-autofix
    versions:
    - 1.0.4
  - dependency-name: react-final-form
    versions:
    - 6.5.3
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: tslib
    versions:
    - 2.1.0
